#!/bin/sh

### BEGIN INIT INFO
# Provides:             button-listener
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Listen for button presses
# Description:          Listen for button presses
### END INIT INFO

PIDFILE=/tmp/button-listener.pid

INSTALL_DIR=/home/pi/uwr-club-control-2019/pi
LOG_FILE=/home/pi/uwr-club-control-2019/logs/button-listener.log


do_start () {
	/usr/bin/python3 $INSTALL_DIR/button-listener.py >> $LOG_FILE & echo $!>$PIDFILE
    #/usr/bin/python3 $INSTALL_DIR/button-listener.py & echo $!>$PIDFILE
}

do_stop () {
    kill $(cat $PIDFILE)
}

case "$1" in
  start)
        do_start
        ;;

  restart|reload|force-reload)
        do_stop
        sleep 1
        do_start
        ;;

  stop)
        do_stop
        ;;

  *)
        echo "Usage: button-listener {start|stop|restart|reload|force-reload}" >&2
        exit 1
esac

exit 0

