#!/bin/sh

### BEGIN INIT INFO
# Provides:		pi-control
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Run Pi control program
# Description:		Run Underwater Robotics Club 2019 Pi control program
### END INIT INFO

PIDFILE=/tmp/pi-control.pid

INSTALL_DIR=/home/pi/uwr-club-control-2019/pi
LOG_FILE=/home/pi/uwr-club-control-2019/logs/pi-control.log


do_start () {
	/usr/bin/python3 $INSTALL_DIR/pi-control.py >> $LOG_FILE & echo $!>$PIDFILE
	#/usr/bin/python3 $INSTALL_DIR/pi-control.py & echo $!>$PIDFILE
}

do_stop () {
	kill $(cat $PIDFILE)
}

case "$1" in
  start)
	do_start
	;;

  restart|reload|force-reload)
	do_stop
	sleep 1
	do_start
	;;

  stop)
	do_stop
	;;

  *)
	echo "Usage: pi-control {start|stop|restart|reload|force-reload}" >&2
	exit 1
esac

exit 0
